In [1]:
import numpy as np

In [4]:
# Assignment A — Implement ReLU and Sigmoid
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z = np.random.randn(3, 3)
print(Z)
print(relu(Z))
print(sigmoid(Z))

[[-0.15666411  0.99322629 -2.56511275]
 [ 0.12918085  0.50045259  0.39846797]
 [ 1.6406061   1.56478415  1.34606832]]
[[0.         0.99322629 0.        ]
 [0.12918085 0.50045259 0.39846797]
 [1.6406061  1.56478415 1.34606832]]
[[0.46091388 0.7297247  0.07141774]
 [0.53225038 0.62256569 0.59831952]
 [0.83761739 0.82703878 0.7934861 ]]


In [5]:
# Assignment B — Build a 2-Layer Neural Network (Forward Pass Only)
X  = np.random.randn(8, 3)
W1 = np.random.randn(3, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 1)
b2 = np.random.randn(1)

# Layer 1
Z1 = X @ W1 + b1
A1 = relu(Z1)

# Layer 2
Z2 = A1 @ W2 + b2
Y = sigmoid(Z2)

print(Y)

[[0.16295894]
 [0.397476  ]
 [0.41437068]
 [0.90937478]
 [0.01685076]
 [0.95184411]
 [0.50268181]
 [0.82087896]]


In [13]:
# Assignment C — Vector Statistics (AI Version)
def vector_norm(x):
    return np.sqrt(np.sum(x**2))

def normalize_vector(x):
    return x / vector_norm(x)

def cosine_similarity(x, y):
    return np.dot(x, y) / (vector_norm(x) * vector_norm(y))

x = np.array([3, -4])
y = np.array([3, 2])
print(vector_norm(x))   # 5.0
print(normalize_vector(x))
print(cosine_similarity(x, y))

x = np.random.randn(512)
y = np.random.randn(512)

print("‖x‖ =", vector_norm(x))
print("‖normalize(x)‖ =", vector_norm(normalize_vector(x)))
print("cos(x, y) =", cosine_similarity(x, y))


5.0
[ 0.6 -0.8]
0.05547001962252291
‖x‖ = 21.57179247086279
‖normalize(x)‖ = 0.9999999999999999
cos(x, y) = -0.004971862312170491


In [27]:
# Assignment D — Data Matrix Analytics
data = np.random.randn(4, 6)   # 4 samples, 6 features each

print(F"Mean: {np.mean(data, axis=0)}")
print(f"Variance: {np.var(data, axis=0)}")
print(f"L2 norm: {np.linalg.norm(data, axis=0)}")
print(f"Normalize each sample to unit norm: {data / np.linalg.norm(data, axis=1, keepdims=True)}")
print(f"Correlation matrix using np.corrcoef(data): {np.corrcoef(data, rowvar=False)}")

Mean: [ 0.17308414 -0.17966215  0.25096077  0.20873139 -0.38848902  0.70481654]
Variance: [0.39461312 1.5148462  0.5068979  0.12673851 1.21380272 1.33535773]
L2 norm: [1.30318263 2.48766935 1.50980689 0.82536611 2.33643013 2.70711956]
Normalize each sample to unit norm: [[ 0.49323109 -0.22143786 -0.55128242 -0.02786101 -0.60494015 -0.19247659]
 [-0.26286057 -0.65714048  0.2081948  -0.06556439 -0.57346438  0.35009363]
 [ 0.25510597  0.64212889  0.42168503  0.20626792  0.51617997 -0.1891691 ]
 [ 0.06032073  0.18650515  0.19050089  0.2618289   0.1176542   0.91809028]]
Correlation matrix using np.corrcoef(data): [[ 1.          0.70503038 -0.59736571  0.3236265   0.4973918  -0.51022658]
 [ 0.70503038  1.          0.13297905  0.81492199  0.96561496 -0.15644887]
 [-0.59736571  0.13297905  1.          0.37030282  0.3852422   0.38237641]
 [ 0.3236265   0.81492199  0.37030282  1.          0.86615317  0.44425339]
 [ 0.4973918   0.96561496  0.3852422   0.86615317  1.         -0.026867  ]
 [-0.5102

In [28]:
import numpy as np

data = np.random.randn(4, 6)

# 1. Mean per feature
mean_per_feature = np.mean(data, axis=0)

# 2. Variance per feature
var_per_feature = np.var(data, axis=0)

# 3. L2 norm per sample
l2_per_sample = np.linalg.norm(data, axis=1)

# 4. Normalize each sample to unit norm
normalized_data = data / np.linalg.norm(data, axis=1, keepdims=True)

# 5. Correlation matrix
corr_matrix = np.corrcoef(data, rowvar=False)

print("Mean per feature:\n", mean_per_feature)
print("\nVariance per feature:\n", var_per_feature)
print("\nL2 norm per sample:\n", l2_per_sample)
print("\nNormalized data:\n", normalized_data)
print("\nCorrelation matrix:\n", corr_matrix)


Mean per feature:
 [ 1.13969821 -0.2441748  -0.11336336 -0.04313864  0.58590107  0.5030828 ]

Variance per feature:
 [0.19853994 0.76989677 2.23341796 0.0543243  2.97017885 0.53895074]

L2 norm per sample:
 [3.47759835 2.44769603 1.37206752 3.86939665]

Normalized data:
 [[ 0.40360447  0.34088764  0.59465947 -0.07926592 -0.42560373  0.42409616]
 [ 0.33977517 -0.19459803  0.04943378 -0.09439809  0.89865357  0.16658782]
 [ 0.43811252 -0.34914798 -0.39777654  0.22424485 -0.54967268 -0.41892855]
 [ 0.44514235 -0.31188275 -0.54185782  0.00684324  0.61462822  0.18207929]]

Correlation matrix:
 [[ 1.          0.00914651 -0.15746853 -0.36552578  0.23568816  0.75180593]
 [ 0.00914651  1.          0.96753145 -0.5356816  -0.78343448  0.57076256]
 [-0.15746853  0.96753145  1.         -0.60361514 -0.6895225   0.49308918]
 [-0.36552578 -0.5356816  -0.60361514  1.         -0.10469876 -0.83594592]
 [ 0.23568816 -0.78343448 -0.6895225  -0.10469876  1.         -0.07032831]
 [ 0.75180593  0.57076256  0.4