In [2]:
# Introduction to NumPy Arrays
import numpy as np

# 1D vector
v = np.array([1, 2, 3])
print("Vector v:", v)
print("Shape:", v.shape)
print("Type:", v.dtype)

# 2D matrix
M = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\nMatrix M:\n", M)
print("Shape:", M.shape)

Vector v: [1 2 3]
Shape: (3,)
Type: int64

Matrix M:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [3]:
# Basic Operations (Elementwise)
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)      # elementwise
print("a / b =", a / b)
print("a ** 2 =", a ** 2)

a + b = [11 22 33]
a - b = [ 9 18 27]
a * b = [10 40 90]
a / b = [10. 10. 10.]
a ** 2 = [100 400 900]


In [7]:
# Dot Product & Matrix Multiplication
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

dot = np.dot(x, y)
matmul = x @ y  # same as dot product for 1D

print("Dot product:", dot)
print("Matmul operator:", matmul)

# matrix × vector
M = np.array([[1, 2, 3],
              [4, 5, 6]])

v = np.array([1, 1, 1])

print("M @ v =", M @ v)

Dot product: 32
Matmul operator: 32
M @ v = [ 6 15]


In [8]:
# Slicing & Indexing
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("First row:", A[0])
print("Last row:", A[-1])
print("First column:", A[:, 0])
print("Submatrix 2x2:\n", A[:2, :2])

First row: [10 20 30]
Last row: [70 80 90]
First column: [10 40 70]
Submatrix 2x2:
 [[10 20]
 [40 50]]


In [4]:
# Broadcasting (CRITICAL for Deep Learning)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

A_plus_b = A + b
A_plus_b

c = np.array([[100],
              [200]])

A + c


array([[101, 102, 103],
       [204, 205, 206]])

In [8]:
# Build a Mini “Linear Layer” in NumPy
# X: (batch_size, in_features)
# W: (in_features, out_features)
# b: (out_features,)

X = np.array([[1, 2, 3],
              [4, 5, 6]])      # shape = (2, 3)

W = np.array([[0.1, 0.2],
              [0.3, 0.4],
              [0.5, 0.6]])     # shape = (3, 2)

b = np.array([1.0, -1.0])       # shape = (2,)

Y = X @ W + b
print("Output Y:\n", Y)

def linear_forward(X, W, b):
    return X @ W + b

X = np.random.randn(5, 3)       # minibatch of 5, 3 features
W = np.random.randn(3, 4)       # 4 output units
b = np.random.randn(4)          # bias for each output unit

print(f"X = {X}\nW = {W}\nb = {b}\n")
Y = linear_forward(X, W, b)
Y, Y.shape


Output Y:
 [[3.2 1.8]
 [5.9 5.4]]
X = [[ 1.55597986  1.11313256  0.91092994]
 [ 1.20953146 -0.75766336  0.26497246]
 [-1.04408275  0.81868357 -0.26745604]
 [ 0.97436932  2.21589961  1.12799853]
 [ 1.73598749 -0.82418005 -0.63177859]]
W = [[ 0.64235346  1.43957028 -0.45443171  0.83480608]
 [-1.26876728  0.60128016  1.04319806 -1.07273379]
 [ 0.61209377  0.01654131  0.71728575 -0.22870105]]
b = [ 0.58017873  0.70654352 -0.84932034  0.09633719]



(array([[ 0.72493614,  3.63085838,  0.25820786, -0.00714691],
        [ 2.48061192,  1.99656409, -1.99930176,  1.85823302],
        [-1.29291854, -0.30865285,  0.28735067, -1.59233148],
        [-0.91495182,  3.46025168,  1.82861478, -1.72529821],
        [ 2.35428125,  2.69960595, -2.95115692,  2.57416432]]),
 (5, 4))